### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by MangKlutz** [MangKlutz/MangKlutz.github.io#23]
Create a webpage that will show the different contents of the site (Products and Services). Make sure to implement external css and native js. Please do not use Javascript templates.

**Comment by kabeer95** [comment]
Hey  I can make it for you,
To create a webpage that showcases the different contents of the site, including Products and Services, I can use HTML, CSS, and native JavaScript. I will start by creating an HTML file that includes a navigation bar with links to the Products and Services sections, as well as a search bar. The Products and Services sections are represented by separate HTML sections, each containing an unordered list of items. Then I will create an external CSS file, style.css, to add styles to our HTML elements, such as layout, colors, and fonts. Finally, will create an external JavaScript file, script.js, to add interactivity to our webpage, in this case, a search functionality that logs the search input value to the console when the search button is clicked. By separating our code into three files, I  can easily maintain and update your webpage without affecting the other components.
